### ISSUE TITLE
Inode unchanged

### ISSUE THREAD

**Issue by Seluj78** [jgigault/42FileChecker#115]
This issue references #51 #67 and #95.

The inode won't change if the file content doesn't change.

I've tried to reproduce the error and didn't suceed : https://asciinema.org/a/bStOKeZVAqF3RPlYfEQUxJLeN

**Comment by DamianDominoDavis** [comment]
Not sure if you still maintain this, but I've successfully reproduced it only on certain machines. With no change to a makefile that can proc the error, one set of machines consistently give the bad inode result, and the other set consistently pass the tests unremarked. From this I conclude the bug is dependent upon the system where it is implemented.
