### ISSUE TITLE
make all twice returns false error

### ISSUE THREAD

**Issue by gtdudu** [jgigault/42FileChecker#7]
Hi,

While running make all twice in a row i get the message make[1]: nothing to be done for "all" but your test returns an error. I believe checking if RET0 and RET2 are both different from "" (line 71) in makefile.sh is the source of the error, because they actually both return " " when running make all twice. Not sure why that is tho. :D

**Comment by jgigault** [comment]
Hey,
The test is checking if RET0 "OR" RET2 are different from "", not "AND" like you mentioned. 
But I think that the problem was coming from the grep command of RET0, your return message was not equivalent with "make: Nothing to be done" because of "[1]" and the lack of capital on the word "nothing".
Could you test again with my update?

**Comment by gtdudu** [comment]
hey,

All good now ! thx for the update.
