### ISSUE TITLE
ft_printf => basictests: Can't compile

### ISSUE THREAD

**Issue by Nihilivin** [jgigault/42FileChecker#85]
Hi there,
First, thanks for that helpful tool. It is really great to save time on most of the tests
I am encountering a little issue while doing basic tests on ft_printf: it seems to not compile with my libft. Does the script expects the lib to be in a particular place? For now I have it in libft/libft.a.

Thank you for your help ;)

**Comment by jgigault** [comment]
Hello and thanks for your issue!
The project "ft_printf" consists in making a library called "libftprintf.a" that is standalone. You must include your dependencies from "libft.a" inside this library.
Within your next projects you will be authorized to have twice libraries "libft.a" and "libftprintf.a" separated.

**Comment by Nihilivin** [comment]
Okay, so I have to building both my  libft & my printf in the same lib. I have not read that anywhere, I think.... If this is the case, it would be great to write it if there's a build error.
Thank you !

**Comment by jgigault** [comment]
Re!
The subject says "Your must submit a Makefile which will compile a libftprintf.a. This lib will be linked to our testing main to give you your results." so that if I strictly follow this instruction I am not allowed to push a secondary dependency.
In my opinion your solution is nice but you won't pass the 42 automatic tests called "moulinette".

**Comment by Nihilivin** [comment]
Fine, thank you very much!
