### ISSUE TITLE
Doesn't work well on arch

### ISSUE THREAD

**Issue by FauconFan** [jgigault/42FileChecker#97]
I leave this message it's maybe the same error as in ubuntu in another issue.
The first thing is that :

tput: unknown terminfo capability 'cd'

My system doesn't know the command open so i can not make the project, i cannot compile some unit test too...

includes/display/display_menu.sh: line 96: open: command not found

I do not understand why it is crashing cause there is no command open in this line... maybe it's hidden then i don't have the level to correct this : HELP !

**Comment by Seluj78** [comment]
That should be fixed with ccf8d390e6a6e9bd86be1f758b9ae711a3bcabf3

Can you confirm ?

and `open` is a command that you won't find on ArchLinux because it is supposed to open the requested file on an external editor on a desktop UI. So that's why you won't have this on Arch. But if you just want to see the file, just go in the root folder of 42fc and find the `.XXX` file corresponding to the test and cat it

**Comment by Seluj78** [comment]
#84
